# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: ["michelmetran"]


# Replace with a single Patreon username
#patreon: michelmetran


# Replace with a single Liberapay username
#liberapay: michelmetran


# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: abre.ai/paypal-mm
# https://www.paypal.com/donate/?business=D7PTKY8VB48G2&no_recurring=0&item_name=Contribui-a+com+um+desenvolvedor+de+projetos+de+c%C3%B3digo+aberto%21%21&currency_code=BRL
# https://
